//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GatoRPCEncode.ECCI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ECCI_B77519_B72097_Gato", ConfigurationName="ECCI.ECCI_B77519_B72097_GatoPort")]
    public interface ECCI_B77519_B72097_GatoPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:jugarRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:jugarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void jugar(int casilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:jugarRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:jugarResponse")]
        System.Threading.Tasks.Task jugarAsync(int casilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:juegaMaquinaRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:juegaMaquinaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int juegaMaquina();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:juegaMaquinaRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:juegaMaquinaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> juegaMaquinaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:checkWinRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:checkWinResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool checkWin(int casilla, string simbolo);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:checkWinRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:checkWinResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> checkWinAsync(int casilla, string simbolo);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:checkCasillasRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:checkCasillasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void checkCasillas(int casilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:checkCasillasRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:checkCasillasResponse")]
        System.Threading.Tasks.Task checkCasillasAsync(int casilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getCasillasRestantesReque" +
            "st", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getCasillasRestantesRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int getCasillasRestantes();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getCasillasRestantesReque" +
            "st", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getCasillasRestantesRespo" +
            "nse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> getCasillasRestantesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:setJugadorRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:setJugadorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void setJugador(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:setJugadorRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:setJugadorResponse")]
        System.Threading.Tasks.Task setJugadorAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getBoardRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getBoardResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getBoard();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getBoardRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getBoardResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getBoardAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:reiniciarRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:reiniciarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void reiniciar(int duracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:reiniciarRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:reiniciarResponse")]
        System.Threading.Tasks.Task reiniciarAsync(int duracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:guardarRecordsRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:guardarRecordsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void guardarRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:guardarRecordsRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:guardarRecordsResponse")]
        System.Threading.Tasks.Task guardarRecordsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getRecordJugadoresRequest" +
            "", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getRecordJugadoresRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getRecordJugadores();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getRecordJugadoresRequest" +
            "", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getRecordJugadoresRespons" +
            "e")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getRecordJugadoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getRecordTiemposRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getRecordTiemposResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getRecordTiempos();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getRecordTiemposRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getRecordTiemposResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getRecordTiemposAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:guardarResultadosRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:guardarResultadosResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void guardarResultados(int duracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:guardarResultadosRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:guardarResultadosResponse" +
            "")]
        System.Threading.Tasks.Task guardarResultadosAsync(int duracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getTopRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getTopResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getTop();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getTopRequest", ReplyAction="urn:ECCI_B77519_B72097_Gato:ECCI_B77519_B72097_GatoPort:getTopResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getTopAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ECCI_B77519_B72097_GatoPortChannel : GatoRPCEncode.ECCI.ECCI_B77519_B72097_GatoPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ECCI_B77519_B72097_GatoPortClient : System.ServiceModel.ClientBase<GatoRPCEncode.ECCI.ECCI_B77519_B72097_GatoPort>, GatoRPCEncode.ECCI.ECCI_B77519_B72097_GatoPort {
        
        public ECCI_B77519_B72097_GatoPortClient() {
        }
        
        public ECCI_B77519_B72097_GatoPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ECCI_B77519_B72097_GatoPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ECCI_B77519_B72097_GatoPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ECCI_B77519_B72097_GatoPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void jugar(int casilla) {
            base.Channel.jugar(casilla);
        }
        
        public System.Threading.Tasks.Task jugarAsync(int casilla) {
            return base.Channel.jugarAsync(casilla);
        }
        
        public int juegaMaquina() {
            return base.Channel.juegaMaquina();
        }
        
        public System.Threading.Tasks.Task<int> juegaMaquinaAsync() {
            return base.Channel.juegaMaquinaAsync();
        }
        
        public bool checkWin(int casilla, string simbolo) {
            return base.Channel.checkWin(casilla, simbolo);
        }
        
        public System.Threading.Tasks.Task<bool> checkWinAsync(int casilla, string simbolo) {
            return base.Channel.checkWinAsync(casilla, simbolo);
        }
        
        public void checkCasillas(int casilla) {
            base.Channel.checkCasillas(casilla);
        }
        
        public System.Threading.Tasks.Task checkCasillasAsync(int casilla) {
            return base.Channel.checkCasillasAsync(casilla);
        }
        
        public int getCasillasRestantes() {
            return base.Channel.getCasillasRestantes();
        }
        
        public System.Threading.Tasks.Task<int> getCasillasRestantesAsync() {
            return base.Channel.getCasillasRestantesAsync();
        }
        
        public void setJugador(string nombre) {
            base.Channel.setJugador(nombre);
        }
        
        public System.Threading.Tasks.Task setJugadorAsync(string nombre) {
            return base.Channel.setJugadorAsync(nombre);
        }
        
        public string getBoard() {
            return base.Channel.getBoard();
        }
        
        public System.Threading.Tasks.Task<string> getBoardAsync() {
            return base.Channel.getBoardAsync();
        }
        
        public void reiniciar(int duracion) {
            base.Channel.reiniciar(duracion);
        }
        
        public System.Threading.Tasks.Task reiniciarAsync(int duracion) {
            return base.Channel.reiniciarAsync(duracion);
        }
        
        public void guardarRecords() {
            base.Channel.guardarRecords();
        }
        
        public System.Threading.Tasks.Task guardarRecordsAsync() {
            return base.Channel.guardarRecordsAsync();
        }
        
        public string getRecordJugadores() {
            return base.Channel.getRecordJugadores();
        }
        
        public System.Threading.Tasks.Task<string> getRecordJugadoresAsync() {
            return base.Channel.getRecordJugadoresAsync();
        }
        
        public string getRecordTiempos() {
            return base.Channel.getRecordTiempos();
        }
        
        public System.Threading.Tasks.Task<string> getRecordTiemposAsync() {
            return base.Channel.getRecordTiemposAsync();
        }
        
        public void guardarResultados(int duracion) {
            base.Channel.guardarResultados(duracion);
        }
        
        public System.Threading.Tasks.Task guardarResultadosAsync(int duracion) {
            return base.Channel.guardarResultadosAsync(duracion);
        }
        
        public string getTop() {
            return base.Channel.getTop();
        }
        
        public System.Threading.Tasks.Task<string> getTopAsync() {
            return base.Channel.getTopAsync();
        }
    }
}
